source 'https://rubygems.org'

# Specify your gem's dependencies in ncode-syosetu.gemspec
gemspec

gem "ncode-syosetu-core", path: "../ncode-syosetu-core"
gem "ncode-syosetu-epub3", path: "../ncode-syosetu-epub3"
gem "ncode-syosetu-mobi", path: "../ncode-syosetu-mobi"
gem "ncode-syosetu-ssml", path: "../ncode-syosetu-ssml"
gem "ncode-syosetu-polly", path: "../ncode-syosetu-polly"
