#!/usr/bin/env ruby

$LOAD_PATH.unshift File.expand_path('../../lib', __FILE__)
require 'ncode-syosetu-polly'

if ARGV.size == 0
  puts "#$0 ncode episode_nubmer"
  exit
end

arg, episode_number = ARGV
parsed = NcodeSyosetu.parse_url(arg)

episode = NcodeSyosetu.client(host: parsed[:host]).get_episode(parsed[:ncode], "dummy_title", episode_number)

builder = NcodeSyosetu::Builder::Polly.new(logger: Logger.new(STDOUT))
builder.write_episode(episode, "#{parsed[:ncode]}-#{episode_number}.mp3")
