#!/usr/bin/env ruby

$LOAD_PATH.unshift File.expand_path('../../lib', __FILE__)
require 'ncode-syosetu-ssml'

if ARGV.size == 0
  puts "#$0 ncode episode_number"
  exit
end

arg, episode_number = ARGV
parsed = NcodeSyosetu.parse_url(arg)

episode = NcodeSyosetu.client(host: parsed[:host]).get_episode(parsed[:ncode], "dummy_title", episode_number)
File.write("#{parsed[:ncode]}-#{episode_number}.ssml", episode.ssml)
